### PR TITLE
Release 1.30.5 December 2022 Export Updates

### PR DESCRIPTION
**Pull request by Meowcenary**
Small release since there are currently no outstanding tickets.

- Script to export list of all collections
- Once again titlecasing Josh Elder's email (ugh)
- Multiple additions to Prism community JSON (thanks for the help @kglibrarian !)

### CODE REVIEW

**Comment by Meowcenary** [comment]
I was supposed to have this ready on Friday, but the day got away from me. I'll plan on merging this tomorrow around noon or so.

**Comment by fenekku** [comment]
@Meowcenary actually do you mind waiting for MeSH terms to be updated? This task: https://github.com/galterlibrary/digital-repository/issues/1151

**Comment by Meowcenary** [comment]
> @Meowcenary actually do you mind waiting for MeSH terms to be updated? This task: #1151

I was planning on waiting until lunchtime so no problems here. I'll review that now and we can coordinate over slack for when it's a good time to merge.

**Review by mattbaumann1 — APPROVED** [review]

**Review by carsonicator — APPROVED** [review]
Thanks @Meowcenary

**Pull request merged**
