### PR TITLE
Release 1.15.0-disable_Original_Publisher-update_and_institutionalize_scripts

### PR DESCRIPTION
**Pull request by sharpattack**
Batch update for Publisher field script needs to be run. The rest were manually uploaded to the server and already run.

### CODE REVIEW

**Comment by sharpattack** [comment]
This is on staging, and `batch_metadata_updates_655.rb` has been successfully run.

**Comment by jpastva** [comment]
@fenekku _Galter Health Sciences Library_ and _Galter Health Sciences Library & Learning Center_ should be kept separate. The shorter name was our official name in use at the time of the launch of DigitalHub, and the longer one is the result of a name change and is currently in use. So both are correct.

**Comment by sharpattack** [comment]
Thanks for confirming @jpastva 
@fenekku the change to "Publisher" will happen in an upcoming PR.

**Comment by fenekku** [comment]
@jpastva thanks for the information. Why isn't the name changed retroactively? Both Galter Health Sciences Library and Galter Health Sciences Library & Learning Center refer to the same institution. Versioning could help keep history here. For DigitalHub it is fine. I am thinking mostly about the new system and how it is a minor annoyance + visually messy to filter by a publisher, just to realize there are variations on that publisher.

@sharpattack ok for the Publisher change.

**Comment by jpastva** [comment]
@fenekku This is standard cataloging practice, to record the name of the publisher at the time a resource was published. I agree that this is somewhat annoying for filtering, but changing the practice would open a whole other can of worms (database maintenance for any other publisher changes, the potential for misleading information if a name change was more dramatic, etc.). Typically name authority records are useful in sorting out relationships when names change, though I'm not sure how they could be leveraged in the new system.

**Pull request merged**
