### PR TITLE
[#1178, #1144] Remove GoogleAnalytics and NewRelic

### LINKED ISSUE #1144: Remove NewRelic
Should be done after/with switch to prism. 

Our billing is most host based, with limited hours per month. Even if we stay within limits, we likely do not want to monitor DigitalHub with NewRelic anymore. We still have google analytics, and solarwinds.

### LINKED ISSUE #1178: Remove/Disable Google Analytics

### PR DESCRIPTION
**Pull request by sharpattack**
Remove google analytics tracking and newrelic monitoring. closes #1178 and closes #1144

### CODE REVIEW

**Comment by sharpattack** [comment]
Marking this "HOLD" for now. We will wait until FSMIT implements redirects for digitalhub, and watch for it's impact on google analytics and new relic. 

The changes for google analytics will stop tracking data, it should not affect historical views/downloads count. That may not matter anyway since any digitalhub page will be virtually inaccessible.

**Review by fenekku — APPROVED** [review]
:+1:

**Review by carsonicator — APPROVED** [review]
Thanks @sharpattack

**Review by Meowcenary — APPROVED** [review]
Thanks Austin!

**Pull request merged**
