### PR TITLE
Temp revert memoized_mesh.txt

### PR DESCRIPTION
**Pull request by sharpattack**

### CODE REVIEW

**Comment by sharpattack** [comment]
I think whatever was updated in the memoized_mesh.txt did not get committed into production. After this, we can revert this in a separate commit.

**Review by Meowcenary — COMMENTED** [review]
As @fenekku pointed out, we don't want any in the form of https://meshb.nlm.nih.gov/mesh/D000038

**Comment by Meowcenary** [comment]
oh, I see. Approving

**Review by Meowcenary — APPROVED** [review]

**Review by fenekku — APPROVED** [review]
Got it. Just reiterating the steps:

1- merge this onto master
2- rebase release on it
3- merge release onto production
4- re-introduce the good mesh changes onto master
5- make new release/rebase release
6- merge release onto production

**Pull request merged**
