### PR TITLE
[#1151] Update MeSH Term Mappings

### LINKED ISSUE #1151: Update MeSH term mappings
Just noting that affected files in DH have been changed. For reference, the relevant headings are below. None of the other revised headings had been assigned yet in DH, though we should keep them as potential headings for new items.

| ID | Old | New |
| --- | --- | --- |
| D001741 | African Americans | Black or African American |
| D000671 | Amputation | Amputation, Surgical |
| D001213 | Asian Americans | Asian |
| D044383 | Blacks | Black People |
| D000091202 | Health Disparity, Minority and Vulnerable Populations | Health Disparate, Minority and Vulnerable Populations |
| D006703 | Homeless Persons|  Ill-Housed Persons |
| D019651 | Reconstructive Surgical Procedures | Plastic Surgery Procedures |

### PR DESCRIPTION
**Pull request by Meowcenary**
Update memoized_mesh.json with latest MeSH term mappings. closes #1151

### CODE REVIEW

**Review by mattbaumann1 — APPROVED** [review]

**Review by fenekku — COMMENTED** [review]
This is missing:

Health Disparity, Minority and Vulnerable Populations | Health Disparate, Minority and Vulnerable Populations

Blacks/education | Black People/education

Also, adding the terms (instead of replacing them) might have been safer. Gretchen changed them on DH, but that was a manual change so she may have missed some. And now that we've replaced the terms, the potentially missed ones won't match.

**Comment by Meowcenary** [comment]
> This is missing:
> 
> Health Disparity, Minority and Vulnerable Populations | Health Disparate, Minority and Vulnerable Populations
> 
> Blacks/education | Black People/education
Ugh, first one I managed to overlook because of the similarity 🤦 I think the second one wasn't in the original ticket, but maybe I'm missing something. Either way I can add those quickly.

> Also, adding the terms (instead of replacing them) might have been safer. Gretchen changed them on DH, but that was a manual change so she may have missed some. And now that we've replaced the terms, the potentially missed ones won't match.

Good point, I'll change that.

**Comment by Meowcenary** [comment]
Okay, just went through the list and I think we should be good.

**Review by fenekku — APPROVED** [review]
Thanks!

Black People/education is a combination term: the combination of "Black People" (that changed as listed) and "education". Their respective ids are embedded in the final id. I didn't spot any other combination terms that were used.

**Comment by Meowcenary** [comment]
> Thanks!
> 
> Black People/education is a combination term: the combination of "Black People" (that changed as listed) and "education". Their respective ids are embedded in the final id. I didn't spot any other combination terms that were used.

Ah, that makes sense. I'm clearly not firing on all cylinders this week 😵

**Pull request merged**
